# deploy-work.yml
name: CI

on:
  push:
    branches:  [ main ]   # sub-branch[branch name] 브랜치에서 push 이벤트가 일어났을 때 실행
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules  # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Setting .env
        run: |
          echo "NEXT_PUBLIC_KAKAO_CLIENT_ID=${{ secrets.NEXT_PUBLIC_KAKAO_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_KAKAO_SECRET=${{ secrets.NEXT_PUBLIC_KAKAO_SECRET }}" >> .env
          
          echo "NEXT_PUBLIC_KAKAO_JAVASCRIPT=${{ secrets.NEXT_PUBLIC_KAKAO_JAVASCRIPT }}" >> .env
          
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_SECRET=${{ secrets.NEXT_PUBLIC_GOOGLE_SECRET }}" >> .env
          
          echo "NEXT_PUBLIC_NAVER_CLIENT_ID=${{ secrets.NEXT_PUBLIC_NAVER_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_NAVER_SECRET=${{ secrets.NEXT_PUBLIC_NAVER_SECRET }}" >> .env
          
          echo "NEXT_PUBLIC_LOGIN_CALLBACK_URL_PREFIX=${{ secrets.NEXT_PUBLIC_LOGIN_CALLBACK_URL_PREFIX }}" >> .env
          echo "NEXT_PUBLIC_PASSPHRASE=${{ secrets.NEXT_PUBLIC_PASSPHRASE }}" >> .env
          
          echo "NEXT_PUBLIC_MODE=${{ secrets.NEXT_PUBLIC_MODE }}" >> .env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          cat .env
        
      - name: Install Dependencies # node module install
        run: yarn

      - name: Build # project build
        run: yarn build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: aws s3 sync ./${{ secrets.BUILD_DIRECTORY }} ${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read --delete
